# 通用配置部分
general:
  broker_address: "100.120.27.64"                      # MQTT代理服务器的地址
  port: 1883                                           # MQTT服务器端口
  temp_topic: "temperature_control/temp_data"          # 温度数据的MQTT主题
  pwm_topic: "temperature_control/pwm_control"         # PWM控制的MQTT主题
  target_temp_min: 25                                  # 目标温度的最小值
  target_temp_max: 50                                  # 目标温度的最大值
  algorithm: "Fuzzy"                                  # 使用的算法（可以是"Random", "Fuzzy", "PID", "SAC", "PPO", "DQN", "A2C", "DDPG", "TD3", "TRPO"）
  action_space_type: "box"                             # 动作空间类型，可选值为"box"或"discrete" (目前支持PPO、A2C、TRPO来进行选择)
  discrete_step: 20                                    # 离散步长（单位：%）
  n_eval_episodes: 5                                   # 每次评估的episode数量

# 温度相关配置部分
temp_config:
  max_diff: 15                                         # 最大温差 / choose tatrget temp max_diff
  temp_tolerance: 0.3                                  # 温度容差 target_temp_tolerance (target_temp ± tolerance)
  critical_range_steps: 50                             # 临界范围步数
  target_temp_range: 5                                 # choose tatrget temp min_diff 目标温度范围，详见choose_target_temp方法文档
  target_temp_low: 25                                  # target temp的下界，用于创建观测空间
  target_temp_high: 50                                 # target temp的上界，用于创建观测空间
  actual_temp_low: 15                                  # actual temp的下界，用于创建观测空间
  actual_temp_high: 60                                 # actual temp的上界，用于创建观测空间
  cooling_temp_low: 15                                 # cooling temp的下界，用于创建观测空间
  cooling_temp_high: 60                                # cooling temp的上界，用于创建观测空间

# 添加dist_config配置块
dist_config:
  dist_max: 20                                         # 随机数值上界（单位%）
  dist_min: 10                                          # 随机数值下界（单位%）
  step_duration: 3                                     # 每次随机数值持续多少步
  chance_of_zero: 0.2                                  # zero数值出现的概率（20%）

# random配置部分
random:
  total_timesteps: 25000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数

# fuzzy配置部分
fuzzy:
  total_timesteps: 25000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数

# PID配置部分
pid:
  total_timesteps: 25000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数  
  kp: 1.0                                              # PID控制器的比例系数
  ki: 0.1                                              # PID控制器的积分系数
  kd: 0.05                                             # PID控制器的微分系数  

# SAC配置部分
sac:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  buffer_size: 1000000                                 # 默认值：1000000   # 经验回放缓存的大小
  learning_rate: 0.0001                                # 默认值：0.0003    # 学习率
  learning_starts: 1000                                # 默认值：100       # 开始学习前的步数（用于初始化回放缓冲区）
  batch_size: 256                                      # 默认值：256       # 批次大小
  tau: 0.005                                           # 默认值：0.005     # 软更新的系数
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子，用于计算未来奖励的当前价值
  train_freq: 1                                        # 默认值：1         # 训练频率（每多少步训练一次）
  gradient_steps: 1                                    # 默认值：1         # 每次训练时的梯度步数
  action_noise: null                                   # 默认值：null      # 动作噪声
  replay_buffer_class: null                            # 默认值：null      # 回放缓冲区类
  replay_buffer_kwargs: null                           # 默认值：null      # 回放缓冲区参数
  optimize_memory_usage: false                         # 默认值：false     # 优化内存使用
  ent_coef: "auto"                                     # 默认值：“auto”    # 熵系数，如果设置为“auto”，算法会自动调整
  target_update_interval: 1                            # 默认值：1         # 目标网络更新间隔
  target_entropy: "auto"                               # 默认值：“auto”    # 目标熵
  use_sde: true                                        # 默认值：false     # 使用状态依赖探索
  sde_sample_freq: -1                                  # 默认值：-1        # 状态依赖探索的采样频率
  use_sde_at_warmup: true                              # 默认值：false     # 在预热期间使用状态依赖探索
  stats_window_size: 100                               # 默认值：100       # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度（0：无输出，1：偶尔输出，2：每步都输出）
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备（cpu, cuda, auto）

# PPO配置部分
ppo:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.0003                                # 默认值：0.0003    # 学习率
  n_steps: 2048                                        # 默认值：2048      # 更新策略之前收集的样本数量
  batch_size: 64                                       # 默认值：64        # 批次大小
  n_epochs: 10                                         # 默认值：10        # 每次更新时的优化轮数
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子
  gae_lambda: 0.95                                     # 默认值：0.95      # GAE lambda
  clip_range: 0.2                                      # 默认值：0.2       # 剪切范围
  clip_range_vf: null                                  # 默认值：null      # 值函数的剪切范围
  normalize_advantage: true                            # 默认值：true      # 标准化优势函数
  ent_coef: 0.0                                        # 默认值：0.0       # 熵系数
  vf_coef: 0.5                                         # 默认值：0.5       # 值函数损失系数
  max_grad_norm: 0.5                                   # 默认值：0.5       # 最大梯度范数
  use_sde: true                                        # 默认值：false     # 使用状态依赖探索
  sde_sample_freq: -1                                  # 默认值：-1        # 状态依赖探索的采样频率
  rollout_buffer_class: null                           # 默认值：null      # 回放缓冲区类
  rollout_buffer_kwargs: null                          # 默认值：null      # 回放缓冲区参数
  target_kl: null                                      # 默认值：null      # 目标KL散度
  stats_window_size: 100                               # 默认值：100       # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度（0：无输出，1：偶尔输出，2：每步都输出）
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备（cpu, cuda, auto）

# DQN配置部分
dqn:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.0001                                # 默认值：0.0001    # 学习率
  buffer_size: 1000000                                 # 默认值：1000000   # 经验回放缓存的大小
  learning_starts: 100                                 # 默认值：100       # 开始学习前的步数
  batch_size: 32                                       # 默认值：32        # 批次大小
  tau: 1.0                                             # 默认值：1.0       # 软更新的系数
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子
  train_freq: 4                                        # 默认值：4         # 训练频率
  gradient_steps: 1                                    # 默认值：1         # 每次训练时的梯度步数
  replay_buffer_class: null                            # 默认值：null      # 回放缓冲区类
  replay_buffer_kwargs: null                           # 默认值：null      # 回放缓冲区参数
  optimize_memory_usage: false                         # 默认值：false     # 优化内存使用
  target_update_interval: 10000                        # 默认值：10000     # 目标网络更新间隔
  exploration_fraction: 0.1                            # 默认值：0.1       # 探索比例
  exploration_initial_eps: 1.0                         # 默认值：1.0       # 初始探索率
  exploration_final_eps: 0.05                          # 默认值：0.05      # 最终探索率
  max_grad_norm: 10                                    # 默认值：10        # 最大梯度范数
  stats_window_size: 100                               # 默认值：100       # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备

# A2C配置部分
a2c:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.0007                                # 默认值：0.0007    # 学习率
  n_steps: 5                                           # 默认值：5         # 更新策略之前收集的样本数量
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子
  gae_lambda: 1.0                                      # 默认值：1.0       # GAE lambda
  ent_coef: 0.0                                        # 默认值：0.0       # 熵系数
  vf_coef: 0.5                                         # 默认值：0.5       # 值函数损失系数
  max_grad_norm: 0.5                                   # 默认值：0.5       # 最大梯度范数
  rms_prop_eps: 1e-5                                   # 默认值：1e-5     # RMSProp的epsilon值
  use_rms_prop: true                                   # 默认值：true      # 是否使用RMSProp优化器
  use_sde: false                                       # 默认值：false     # 使用状态依赖探索
  sde_sample_freq: -1                                  # 默认值：-1        # 状态依赖探索的采样频率
  rollout_buffer_class: null                           # 默认值：null      # 回放缓冲区类
  rollout_buffer_kwargs: null                          # 默认值：null      # 回放缓冲区参数
  normalize_advantage: false                           # 默认值：false     # 标准化优势函数
  stats_window_size: 100                               # 默认值：100       # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度（0：无输出，1：偶尔输出，2：每步都输出）
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备（cpu, cuda, auto）

# DDPG配置部分
ddpg:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.001                                 # 默认值：0.001     # 学习率
  buffer_size: 1000000                                 # 默认值：1000000   # 经验回放缓存的大小
  learning_starts: 100                                 # 默认值：100       # 开始学习前的步数
  batch_size: 256                                      # 默认值：256       # 批次大小
  tau: 0.005                                           # 默认值：0.005     # 软更新的系数
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子
  train_freq: 1                                        # 默认值：1         # 训练频率（每多少步训练一次）
  gradient_steps: 1                                    # 默认值：1         # 每次训练时的梯度步数
  action_noise: null                                   # 默认值：null      # 动作噪声
  replay_buffer_class: null                            # 默认值：null      # 回放缓冲区类
  replay_buffer_kwargs: null                           # 默认值：null      # 回放缓冲区参数
  optimize_memory_usage: false                         # 默认值：false     # 优化内存使用
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备

# TD3配置部分
td3:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.001                                 # 默认值：0.001     # 学习率
  buffer_size: 1000000                                 # 默认值：1000000   # 经验回放缓存的大小
  learning_starts: 100                                 # 默认值：100       # 开始学习前的步数
  batch_size: 256                                      # 默认值：256       # 批次大小
  tau: 0.005                                           # 默认值：0.005     # 软更新的系数
  gamma: 0.99                                          # 默认值：0.99      # 折扣因子
  train_freq: 1                                        # 默认值：1         # 训练频率（每多少步训练一次）
  gradient_steps: 1                                    # 默认值：1         # 每次训练时的梯度步数
  action_noise: null                                   # 默认值：null      # 动作噪声
  replay_buffer_class: null                            # 默认值：null      # 回放缓冲区类
  replay_buffer_kwargs: null                           # 默认值：null      # 回放缓冲区参数
  optimize_memory_usage: false                         # 默认值：false     # 优化内存使用
  policy_delay: 2                                      # 默认值：2         # 策略延迟
  target_policy_noise: 0.2                             # 默认值：0.2       # 目标策略噪声
  target_noise_clip: 0.5                               # 默认值：0.5       # 目标噪声剪辑
  stats_window_size: 100                               # 默认值：100       # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null      # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null      # 策略参数
  verbose: 2                                           # 默认值：0         # 日志详细程度
  seed: null                                           # 默认值：null      # 随机种子
  device: "auto"                                       # 默认值：“auto”    # 使用的设备

# TRPO配置部分
trpo:
  total_timesteps: 80000                               # 训练过程中的总时间步数
  episode_max_steps: 500                               # 每个环节的最大步数
  eval_freq: 5000                                      # 评估模型的频率（每多少步进行一次评估）
  save_freq: 5000                                      # 模型保存频率（每多少步保存一次模型）
  learning_rate: 0.001                                 # 默认值：0.001    # 学习率
  n_steps: 2048                                        # 默认值：2048     # 更新策略之前收集的样本数量
  batch_size: 128                                      # 默认值：128      # 批次大小
  gamma: 0.99                                          # 默认值：0.99     # 折扣因子
  cg_max_steps: 15                                     # 默认值：15       # 共轭梯度法的最大迭代步数
  cg_damping: 0.1                                      # 默认值：0.1      # 共轭梯度法的阻尼系数
  line_search_shrinking_factor: 0.8                    # 默认值：0.8      # 线性搜索的收缩因子
  line_search_max_iter: 10                             # 默认值：10       # 线性搜索的最大迭代次数
  n_critic_updates: 10                                 # 默认值：10       # 评论家更新的次数
  gae_lambda: 0.95                                     # 默认值：0.95     # GAE lambda
  use_sde: false                                       # 默认值：false    # 使用状态依赖探索
  sde_sample_freq: -1                                  # 默认值：-1       # 状态依赖探索的采样频率
  rollout_buffer_class: null                           # 默认值：null     # 回放缓冲区类
  rollout_buffer_kwargs: null                          # 默认值：null     # 回放缓冲区参数
  normalize_advantage: true                            # 默认值：true     # 标准化优势函数
  target_kl: 0.01                                      # 默认值：0.01     # 目标KL散度
  sub_sampling_factor: 1                               # 默认值：1        # 子采样因子
  stats_window_size: 100                               # 默认值：100      # 统计窗口大小
  tensorboard_log: "./tensorboard/"                    # 默认值：null     # Tensorboard日志路径
  policy_kwargs: null                                  # 默认值：null     # 策略参数
  verbose: 2                                           # 默认值：0        # 日志详细程度（0：无输出，1：偶尔输出，2：每步都输出）
  seed: null                                           # 默认值：null     # 随机种子
  device: "auto"                                       # 默认值："auto"   # 使用的设备（cpu, cuda, auto）